dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: spring-service1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: spring-service10
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: spring-service11
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-service2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: spring-service4
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: spring-service6
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: spring-service8
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
